exports.seed = async function (knex) {
  await knex("measureUnid").insert([
    { unid: "KG", description: "QUILOGRAMA" },
    { unid: "GRAMAS", description: "GRAMAS" },
    { unid: "LITRO", description: "LITRO" },
    { unid: "UNID", description: "UNIDADE" },
    { unid: "GF", description: "GARRAFA" },
    { unid: "LATA", description: "LATA" },
    { unid: "PACOTE", description: "PACOTE" },
    { unid: "KIT", description: "KIT" },
    { unid: "BARRA", description: "BARRA" },
    { unid: "DUZIA", description: "DUZIA" },
    { unid: "VASIL", description: "VASILHAME" },
    { unid: "VIDRO", description: "VIDRO" },
    { unid: "AMPOLA", description: "AMPOLA" },
    { unid: "BALDE", description: "BALDE" },
    { unid: "BANDEJ", description: "BANDEJA" },
    { unid: "BISNAG", description: "BISNAGA" },
    { unid: "CÁPSULAS", description: "CÁPSULA" },
    { unid: "CENTO", description: "CENTO" },
    { unid: "CJ", description: "CONJUNTO" },
    { unid: "CM", description: "CENTÍMETRO" },
    { unid: "CM2", description: "CENTIMETRO QUADRADO" },
    { unid: "CX", description: "CAIXA" },
    { unid: "CX2", description: "CAIXA COM 2 UNIDADES" },
    { unid: "CX3", description: "CAIXA COM 3 UNIDADES" },
    { unid: "CX5", description: "CAIXA COM 5 UNIDADES" },
    { unid: "CX10", description: "CAIXA COM 10 UNIDADES" },
    { unid: "CX15", description: "CAIXA COM 15 UNIDADES" },
    { unid: "CX20", description: "CAIXA COM 20 UNIDADES" },
    { unid: "CX25", description: "CAIXA COM 25 UNIDADES" },
    { unid: "CX50", description: "CAIXA COM 50 UNIDADES" },
    { unid: "CX100", description: "CAIXA COM 100 UNIDADES" },
    { unid: "EMBAL", description: "EMBALAGEM" },
    { unid: "FARDO", description: "FARDO" },
    { unid: "FOLHA", description: "FOLHA" },
    { unid: "FRASCO", description: "FRASCO" },
    { unid: "GALAO", description: "GALÃO" },
    { unid: "JOGO", description: "JOGO" },
    { unid: "M", description: "METRO" },
    { unid: "M2", description: "METRO QUADRADO" },
    { unid: "M3", description: "METRO CÚBICO" },
    { unid: "MILHEI", description: "MILHEIRO" },
    { unid: "ML", description: "MILILITRO" },
    { unid: "PC", description: "PEÇA" },
    { unid: "AMIGO", description: "AMIGO" },
    { unid: "K", description: "QUILATE" },
    { unid: "RESMA", description: "RESMA" },
    { unid: "ROLO", description: "ROLO" },
    { unid: "SACO", description: "SACO" },
    { unid: "SACOLA", description: "SACOLA" },
    { unid: "TON", description: "TONELADA" },
    { unid: "TUBO", description: "TUBO" },
  ]);
};
