exports.seed = async function (knex) {
  await knex("product").insert([
    {
      name: "X-SALADA",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Presunto, 2 queijos (Prato e Mussarela) Hamburguer Artesanal de Costela 150 grama (Rúcula Opcional)",
      price: 25,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-TUDO",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Presunto, 2 queijos (Prato e Mussarela), Bacon, ovo, Hamburguer Artesanal de Costela 150 grama (Rúcula Opcional)",
      price: 35,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-BURGUER",
      description: "",
      ingredient:
        "Pão de hamburguer, 2 queijos (Prato e Mussarela), Hamburguer Artesanal de Costela 150 grama",
      price: 20,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-FRANGO BACON",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Filé de Frango, Bacon crocante, 2 queijos (Prato e Mussarela)",
      price: 25,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "BAURU BACON",
      description: "",
      ingredient:
        "Carne, Tomate, Cebola, 2 queijos (Prato e Mussarela), Bacon crocante, (Rúcula Opcional)",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "BAURU TUDO",
      description: "",
      ingredient:
        "Carne, Tomate, Cebola, 2 Ovos, 2 queijos (Prato e Mussarela), Bacon crocante, (Rúcula Opcional)",
      price: 35,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "HOT DOG FRANGO",
      description: "",
      ingredient: "Salsicha, molho de frango, maionese e catchup, Batata Palha",
      price: 10,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "HOT DOG ESPECIAL",
      description: "",
      ingredient:
        "2 Salsichas, queijo Prato, Molho de frango, Maionese e Catchup, Batata Palha",
      price: 15,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-TOSCANA",
      description: "",
      ingredient:
        "Hamburguer de Toscana 200 grama, 2 queijos (Prato e Mussarela), Tomate (Rúcula opcional)",
      price: 0,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-EGG",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Presunto, 2 queijos (Prato e Mussarela), 2 Ovos, Hamburguer Artesanal de Costela 150 grama (Rúcula Opcional)",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-BACON EGG",
      description: "",
      ingredient:
        "Pão de hamburguer, Presunto, 2 queijos (Prato e Mussarela), Bacon Crocante, 2 Ovos, Hamburguer Artesanal de Costela 150 grama (Rúcula Opcional)",
      price: 35,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-FRANCO",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Filé de Frango, 2 queijos (Prato e Mussarela) - Rúcula Opcional",
      price: 20,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-FRANGO TUDO",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Filé de Frango, Bacon Crocante, ovo, 2 queijos (Prato e Mussarela) - Rúcula Opcional",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "BAURU EGG",
      description: "",
      ingredient:
        "Carne, Tomate, Cebola, 2 queijos (Prato e Mussarela), 2 Ovos - Rúcula Opcional",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "AMERICANO",
      description: "",
      ingredient:
        "Carne, Alface, Tomate, Cebola, 2 queijos (Prato e Mussarela), Presunto, 2 Ovos - Rúcula Opcional",
      price: 35,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "HOT DOG TRADICIONAL",
      description: "",
      ingredient: "2 Salsichas, Molho, Maionese e Catchup e Batata Palha",
      price: 8,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-CALABRESA",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Calabresa em Tiras, Queijo Prato - Cebola Opcional",
      price: 25,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-DELLACY",
      description: "",
      ingredient:
        "Pão de Brioche com gergilim, Cheddar, Bacon Crocante, Hamburguer Artesanal de Costela de 150 grama, Queijo Prato, Rúcula, Tomate, Cream Cheese (catchup)",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-SALADA BACON",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, Presunto, 2 Queijos (Prato e Mussarela), Bacon Crocante, Hamburguer Artesanal de Costela 150 grama - Rúcula Opcional",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "HAMBÚRGUER",
      description: "",
      ingredient:
        "Pão de hamburguer, Batata Palha, 2 Queijos (Prato e Mussarela), Hamburguer Artesanal de Costela 150 grama",
      price: 20,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "X-FRANGO EGG",
      description: "",
      ingredient:
        "Pão de hamburguer, Alface, Tomate, 2 Ovos, Filé de Frango, 2 Queijos (Prato e Mussarela) - Rúcula Opcional",
      price: 25,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "BAURU",
      description: "",
      ingredient:
        "Carne Tomate, Cebola, 2 Queijos (Prato e Mussarela) - Rúcula Opcional",
      price: 30,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "MINI X-SALADA",
      description: "",
      ingredient:
        "Mini Pão de Hamburguer Redondo, Hambuerguer, Alface, Tomante, Presunto, Queijo - Rúcula Opcional",
      price: 9,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "KIDS MINI",
      description: "",
      ingredient:
        "Pão de Hamburguer Redondo, Hambuerguer, Batata Palha, Presunto, Queijo",
      price: 9,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 1,
      measureUnid_id: 4,
      visibleApp: true,
    },
    // BEBIDAS
    // ------------------------------------------------------------------------
    {
      name: "COCA-COLA LATA",
      description: "",
      ingredient: "Coca cola lata 350 ml tradicional",
      price: 8,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 4,
      visibleApp: true,
    },
    {
      name: "COCA-COLA 1 litro",
      description: "",
      ingredient: "Coca cola lata 1 litro tradicional",
      price: 12,
      additional: "",
      image: "default.jpg",
      promotion: false,
      pricePromotion: 0,
      category_id: 2,
      measureUnid_id: 4,
      visibleApp: true,
    },
  ]);
};
